ModelType: acc_predictor

ARCH: resnet18
super_model:
bw_dataset_path:
acc_dataset_path:
acc_model:
Resume:


GPUS:
  - 1

RNG_SEED: 19121


EVAL:
  channel_wise: False
  w_sym: True
  a_sym: False

DATASET:
  data_set: imagenet
  data_path: /data/ImageNet
  train_batch_size: 256
  eval_batch_size: 256
  workers: 8

OPTIM:
  num_epochs: 100
  optimizer: Adam
  momentum: 0.0
  lr: 4.0e-4
  weight_decay: 1.e-5

SEARCH_SPACE:
  channel_wise_list:
    - True
    - False
  w_sym_list:
    - True
    - False
  a_sym_list:
    - True
    - False
  w_bit_list:
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
  a_bit_list:
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8

OUT_DIR: ../ExpNew/

#quantization
quantizer: lsq
levels: 2
w_bit: 8
a_bit: 8

act_quant: True
test_before_calibration: True
disable_8bit_head_stem: False

num_samples: 256
acc_sample: 1000

